seed: 42
device: cuda
data: {root_raw: data/raw, clamp: [-45, 167], input_size: [512, 512], split: {train: 0.8, val: 0.1, test: 0.1}, tumor_only_train: false}
model: {in_channels: 1, out_channels: 1, base_channels: 64}
train: {epochs: 8, batch_size: 4, lr: 1e-5, optimizer: adam, loss: dice, bce_weight: 0.5, num_workers: 4, amp: true}
eval:  {threshold: 0.5}
out_dir: experiments/bs4_ep8_lr1e-5
